import sys
from pathlib import Path

import streamlit as st

# Add project root to Python path
ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from src.assistant import create_assistant
from src.database import save_conversation, save_feedback
from src.judge import evaluate_relevance

st.set_page_config(page_title="Predictive Maintenance RAG Assistant", page_icon="🛠️", layout="wide")

EXAMPLE_QUESTIONS = [
    "What are the symptoms of Tool Wear Failure?",
    "How is Heat Dissipation Failure detected?",
    "What causes Power Failure?",
    "What is the halt criteria for a production line incident?",
    "What fields are needed to diagnose Overstrain Failure?",
]


@st.cache_resource(show_spinner="Loading assistant...")
def get_assistant():
    return create_assistant()


llm_assistant = get_assistant()

# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []  # list of dicts: role, content, ...metrics, feedback


def handle_question(question: str):
    question = question.strip()
    if not question:
        return

    with st.spinner("Thinking..."):
        answer = llm_assistant.rag(question)
        answer_record = llm_assistant.last_call
        relevance, explanation = evaluate_relevance(question, answer)

        # log the conversation + the judge's relevance verdict
        conversation_id = save_conversation(answer_record, question, "General")
        save_feedback(conversation_id, "judge", relevance=relevance, explanation=explanation)

    st.session_state.messages.append({"role": "user", "content": question})
    st.session_state.messages.append({
        "role": "assistant",
        "content": answer,
        "conversation_id": conversation_id,
        "response_time": answer_record.response_time,
        "prompt_tokens": answer_record.prompt_tokens,
        "completion_tokens": answer_record.completion_tokens,
        "cost": answer_record.cost,
        "relevance": relevance,
        "explanation": explanation,
        "feedback": None,
    })


def handle_feedback(conversation_id, feedback: str):
    for msg in st.session_state.messages:
        if msg.get("conversation_id") == conversation_id:
            msg["feedback"] = feedback
            break
    save_feedback(conversation_id, "user", score=1 if feedback == "positive" else -1)


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("🛠️ Predictive Maintenance Assistant")
    st.caption(
        "Retrieval-augmented Q&A over the machine-failure knowledge base. "
        "Answers are generated by an LLM grounded in the retrieved context."
    )

    st.divider()
    st.subheader("Try an example question")
    for q in EXAMPLE_QUESTIONS:
        if st.button(q, key=f"example_{q}", width="stretch"):
            handle_question(q)
            st.rerun()

    st.divider()
    if st.button("🗑️ Clear conversation", width="stretch"):
        st.session_state.messages = []
        st.rerun()

# ---------------------------------------------------------------------------
# Main chat area
# ---------------------------------------------------------------------------
st.title("Predictive Maintenance RAG Assistant")
st.caption(
    "Ask about machine failure modes, sensor signatures, root causes, or recommended actions. "
    "Answers are generated by an LLM grounded in the retrieved knowledge-base context - see the "
    "sidebar to try an example."
)

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

        if msg["role"] == "assistant":
            with st.expander("Answer details"):
                st.markdown(f"**Response time:** {msg['response_time']:.2f}s")
                st.markdown(f"**Prompt tokens:** {msg['prompt_tokens']}")
                st.markdown(f"**Completion tokens:** {msg['completion_tokens']}")
                st.markdown(f"**Cost:** ${msg['cost']:.4f}")
                st.markdown(f"**LLM judge relevance:** {msg['relevance']}")
                st.markdown(f"*{msg['explanation']}*")

            conversation_id = msg.get("conversation_id")
            feedback = msg.get("feedback")
            col1, col2, col3 = st.columns([1, 1, 8])
            if feedback is None:
                if col1.button("👍", key=f"up_{conversation_id}"):
                    handle_feedback(conversation_id, "positive")
                    st.rerun()
                if col2.button("👎", key=f"down_{conversation_id}"):
                    handle_feedback(conversation_id, "negative")
                    st.rerun()
            else:
                emoji = "👍" if feedback == "positive" else "👎"
                col1.markdown(f"Feedback recorded: {emoji}")

user_input = st.chat_input("Ask about a machine failure mode, sensor, or escalation step...")
if user_input:
    handle_question(user_input)
    st.rerun()
